// search_front_end/src/App.jsx
import React from 'react';
import 'bootstrap/dist/css/bootstrap.min.css'
import Navbar from './components/Navbar'
import EmbedTweets from './components/EmbedTweets'
import axios from 'axios';
//Navbar from 'react-bootstrap/Navbar'
import './App.scss';

class App extends React.Component {
  constructor(props) {
    super(props);
    this.state =  {
      showResults : false,
      query: "",
      results: [],
    }
  }

  handleSubmit = event => {
    let url =  'http://localhost:8080/search?query=';
    let query = this.state.query.split(' ').join('+');
    url += query;
    
    axios.get(url)
      .then((response) => {
        if(response.status == 200) {
          this.setState({results: response.data.result})
          console.log(this.state.results);
        }
        this.setState({showResults: true})
      })
    event.preventDefault();
  }

  handleChange = event => {
    this.setState({query: event.target.value});
  }

  reset = event => {
    this.setState({
      showResults : false,
      query: "",
      results: [],
    })
  }

  render() {
    const isHome = this.state.showResults;
    return (
      <div>
        <div className="Base">
          <div className ="layer"></div>
          <div className="Nav">
            <Navbar/>
          </div>
          <div className="content">
            <div>
              {!isHome 
                ?
                  <div className="home">
                    <div className = "title">
                        Your Search Starts With Us.
                    </div>
                    <div className = "search">
                      Enter your search for any tweet below <br/><br/>
                      <form onSubmit={this.handleSubmit}>
                        <label>Query: </label>
                        <input type="text" onChange={this.handleChange} />
                      </form>
                    </div>
                  </div>
                :
                <div>
                  {this.state.results.length === 0
                    ?
                    <div>
                    <div className="norescont">
                        <div className = "title">
                            Curious...
                        </div>
                        <div className = "nores">
                          It seems out of 4.5 million tweets, your search query: <br/>
                          <div className = "query">
                            &nbsp;&nbsp;&nbsp;<i>{this.state.query}</i><br/>
                          </div>
                          does not match any in our collection. <br/>
                          Though this number may seem daunting, the Fall of 2020 was a trying time. <br/>
                          Keeping this in mind, try a more relevant search. <br/> <br/>
                        </div>
                      </div>
                      <div className="btnctr">
                        <button type="button" onClick={this.reset} className="btn">Search Again</button>
                      </div>
                    </div>
                    :
                    <div>
                      <div className="home">
                        <div className = "poem">
                          <i>Tweets from Sea to shining Sea <br/>
                          About the Fall of 2020 for you and me.</i> <br/> <br/>
                        </div>
                      </div>

                      <div className="rightscroll">
                        <div className = "poem">
                          <i>Query: {this.state.query} </i><br/> <br/>
                        </div>
                        <button type="button" onClick={this.reset} className="btn">Search Again</button> <br/>
                      </div>

                      <div className="results">
                        <EmbedTweets results = {this.state.results}/>
                      </div>


                      <button type="button" onClick={this.reset} className="btn">Search Again</button> <br/>
                      
                    </div>
                  }
                </div>
              }
            </div>
          </div>
        </div>
      </div>
    )
  }
}

export default App;

// attempt/src/app/app.component.ts
import { Component } from '@angular/core';
import { HttpClient } from '@angular/common/http';

interface Tweet {
  text: string;
  id: string;
}

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  searchQuery: string = '';
  formattedSearchQuery: string = '';
  tweetIds: string[] = [];
  gotResult: boolean = false;

  title = 'Twitter Search Engine';

  constructor(private http: HttpClient) {}
  
  getSearchQuery(query: string) {
    this.searchQuery = query;
    // Format string and assign it to class variable
    this.formattedSearchQuery = query.trim().toLowerCase().replace(/\s+/g, '+');
    console.log(`Formatted Query String: '${this.formattedSearchQuery}'`);
  }

  parseTweetIds(response: any) {
    const tweets: Tweet[] = response.result;
    this.tweetIds = tweets.map(tweet => tweet.id);

    console.log(
      this.tweetIds.length > 0 ? 
        `Tweet Ids: ${this.tweetIds.join('\n')}` : 
        'No Tweets Returned'
    );
    this.gotResult = true;
  }
  
  getTweetIds(unformattedQuery: string) {
    this.getSearchQuery(unformattedQuery);
    
    const url = 'http://localhost:8080/search';
    const query = this.formattedSearchQuery;
  
    this.http.get(url, { params: { query } })
      .subscribe((response: any) => {
        this.parseTweetIds(response);
      });
  }

  refreshPage() {
    // Use JavaScript's window.location to reload the page
    window.location.reload();
  }
}


<div class="webpage">
  <!-- 
    Banner 
      stays on top of screen even as user scrolls
  -->
  <div class="banner">
    <a class="home-button" href="">
      Twitter Search Engine 
    </a>
    <div class="github-button">
      <a href="https://github.com/athom031/Twitter-Search-Engine" target="_blank" rel="noopener" style="float: right;">
        GitHub Repo
      </a>
      <img src="../assets/github_logo.png" alt="GitHub Logo" class="github-logo">
    </div>
  </div>

  <!-- 
    Search Home 
      when no search query is currently submitted
  -->
  <div *ngIf="!gotResult; else search">
    <div class="search-home-container">
      <div class="search-home-title">
        <p>
          Your Search Starts
          <br/> 
          With Us.
          <br/>
        </p>
      </div>

      <div class="search-home-caption">
        <br/>
        <p>
          Enter your search for any tweet below <br/><br/>
        </p>
      </div> 

      <div class="search-home-bar">
        <p>
          Query:
        </p>
        <app-search-bar (searchSubmit)="getTweetIds($event)"></app-search-bar>
      </div>

    </div>
  </div>

  <!--
    Search Results
      returned relevant tweets based on search query
  -->
  <ng-template #search>
    <div *ngIf="tweetIds.length>0; else no_results">
      <div class="search-results">

        <div class="search-results-query">
          Query: {{ searchQuery }}
        </div>
        
        <div class="search-results-tweets">
          <div *ngFor="let tweetId of tweetIds">
            <app-tweet-embed [tweetId]="tweetId"></app-tweet-embed>
          </div>
        </div>
  
        <div class="search-results-banner">
          Tweets From Sea to Shining Sea
          About the Fall of 2020
          For You and Me.
        </div>
  
      </div>
    </div>

    <ng-template #no_results>
      <div class="no-results-container">
        <div class="no-results-wrapper">
          <div class="no-results-title">
            Curious...
          </div>
          <div class="no-results-body">
            It seems out of 4.5 million tweets, your search query:<br/>
            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<i>{{ searchQuery }}</i><br/>
            does not match any in our collection.<br/><br/>
            Though this number may seem daunting,<br/>
            &nbsp;&nbsp;&nbsp;the Fall of 2020 was a trying time.<br/>
            Keeping this in mind, <br/>
            &nbsp;&nbsp;&nbsp;try a more relevant search.<br/><br/>
          </div>
        </div>

        <div class="search-results-refresh">
          <button class="btn" (click)="refreshPage()">Search Again</button>
        </div>
      </div>
    </ng-template>


    
    
  </ng-template>

  <router-outlet></router-outlet>
</div>
